workflows:
  android-release:
    name: Nexa Android Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.codeme.app"
        GRADLE_OPTS: "-Xmx8G -XX:MaxMetaspaceSize=4G"
    scripts:
      - name: Instalar dependências
        script: |
          flutter pub get

      - name: Build APKs divididos por arquitetura (reduz tamanho)
        script: |
          flutter build apk --debug --split-per-abi

    artifacts:
      - build/app/outputs/flutter-apk/*.apk