name: nexa
description: CodeMe App - Custom UI Native

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  flutter_svg: ^2.0.10+1
  file_picker: ^11.0.3
  image_picker: ^1.2.3
  http: any
  shared_preferences: any

flutter:
  uses-material-design: true
  assets:
    - assets/icons/svg/
    - assets/icons/svg_color/
    - assets/icons/png/
    - assets/editor/docs.html
    - assets/editor/sheets.html
    - assets/editor/slides.html
    - assets/editor/whiteboard.html
    - assets/logo.png