name: codeme_app
description: CodeMe App - Fluent UI Native

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.9.2

flutter:
  uses-material-design: false